name = "Traitor"
uuid = "51d8d3fb-42fa-4eee-8664-c9fdd13ad6d2"
authors = ["Andy Ferris", "Chris Foster"]
version = "0.1.0"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "InteractiveUtils"]
